def on_button_pressed_a():
    global roulette
    music.stop_all_sounds()
    roulette += randint(0, 2)
    for index in range(2):
        LoadScreen()
    if roulette == 0:
        basic.show_string("SAFE")
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.play_tone(220, music.beat(BeatFraction.WHOLE))
        music.play_tone(220, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(247, music.beat(BeatFraction.WHOLE))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.play_tone(220, music.beat(BeatFraction.WHOLE))
        music.play_tone(220, music.beat(BeatFraction.WHOLE))
        basic.pause(400)
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(247, music.beat(BeatFraction.WHOLE))
        music.play_tone(247, music.beat(BeatFraction.HALF))
        music.stop_all_sounds()
    else:
        basic.show_string("Get Ricked")
        music.set_volume(255)
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(466, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(466, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.EIGHTH))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.BREVE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(523, music.beat(BeatFraction.BREVE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.DOUBLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.EIGHTH))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.HALF))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(440, music.beat(BeatFraction.QUARTER))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.play_tone(349, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.play_tone(330, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(262, music.beat(BeatFraction.HALF))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.rest(music.beat(BeatFraction.SIXTEENTH))
        music.play_tone(349, music.beat(BeatFraction.DOUBLE))
        music.rest(music.beat(BeatFraction.WHOLE))
        music.stop_all_sounds()
input.on_button_pressed(Button.A, on_button_pressed_a)

def LoadScreen():
    basic.show_leds("""
        . . # . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        . . . . #
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        . . . . #
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . #
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . # . .
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        # . . . .
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        # . . . .
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        # . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        . . # . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        """)
    basic.show_leds("""
        # # # # #
        # # # # #
        # # # # #
        # # # # #
        # # # # #
        """)
    basic.show_leds("""
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        """)
roulette = 0
roulette = 0

def on_forever():
    pass
basic.forever(on_forever)
